"""The seeded CUE track catalog.

Hand-authored, DJ-realistic metadata for a live South-Asian-diaspora party
floor: Punjabi/bhangra, Bollywood across four decades, Western hip-hop/R&B,
house/techno/EDM, retro disco anthems, and Latin/Afrobeats/Amapiano.

Every categorical field here MUST be a canonical token from ``app.taxonomy`` --
the ranker scores tracks against wave centroids in the shared vector space, so
an off-vocabulary tag is silently invisible rather than merely wrong.

BPMs are the values a DJ would actually see in Rekordbox (hip-hop is listed at
its true half-time tempo where that is the convention -- the ranker knows how
to bridge half/double time). ``energy`` is honest: a ballad is a ballad.
"""

from __future__ import annotations

from typing import List

from ..contracts import Track


def _t(
    id,
    title,
    artist,
    language,
    genres,
    moods,
    era,
    bpm,
    energy,
    danceability,
    popularity,
    duration_sec,
    tags,
):
    return Track(
        id=id,
        title=title,
        artist=artist,
        language=language,
        genres=list(genres),
        moods=list(moods),
        era=era,
        bpm=bpm,
        energy=energy,
        danceability=danceability,
        popularity=popularity,
        duration_sec=duration_sec,
        tags=list(tags),
        audio_file=None,
    )


# ---------------------------------------------------------------------------
# Punjabi / Bhangra / Desi hip-hop
# ---------------------------------------------------------------------------

_PUNJABI: List[Track] = [
    _t("trk_lover_dd", "Lover", "Diljit Dosanjh", "punjabi",
       ["bhangra", "pop"], ["romantic", "celebratory"], "2020s",
       98, 0.62, 0.78, 0.84, 195, ["sing-along", "wedding", "diljit", "sangeet"]),
    _t("trk_goat_dd", "G.O.A.T.", "Diljit Dosanjh", "punjabi",
       ["desi_hiphop", "bhangra"], ["hype", "celebratory"], "2020s",
       100, 0.84, 0.88, 0.82, 205, ["dhol", "peak-time", "swagger", "diljit"]),
    _t("trk_5taara_dd", "5 Taara", "Diljit Dosanjh", "punjabi",
       ["bhangra"], ["hype", "celebratory"], "2010s",
       102, 0.80, 0.86, 0.80, 210, ["dhol", "bhangra-floor", "wedding", "diljit"]),
    _t("trk_doyouknow_dd", "Do You Know", "Diljit Dosanjh", "punjabi",
       ["bhangra", "pop"], ["romantic", "nostalgic"], "2010s",
       92, 0.58, 0.72, 0.78, 220, ["sing-along", "slow-burn", "diljit"]),
    _t("trk_born2shine_dd", "Born To Shine", "Diljit Dosanjh", "punjabi",
       ["desi_hiphop", "bhangra"], ["hype", "aggressive"], "2020s",
       96, 0.86, 0.84, 0.76, 200, ["peak-time", "swagger", "diljit"]),
    _t("trk_patiala_dd", "Patiala Peg", "Diljit Dosanjh", "punjabi",
       ["bhangra"], ["celebratory", "hype"], "2010s",
       98, 0.82, 0.88, 0.79, 215, ["dhol", "daaru", "baraat", "diljit"]),
    _t("trk_laembadgini_dd", "Laembadgini", "Diljit Dosanjh", "punjabi",
       ["bhangra", "desi_hiphop"], ["hype", "celebratory"], "2010s",
       100, 0.83, 0.87, 0.74, 205, ["dhol", "bhangra-floor", "diljit"]),
    _t("trk_brownmunde_ap", "Brown Munde", "AP Dhillon", "punjabi",
       ["desi_hiphop"], ["hype", "celebratory"], "2020s",
       92, 0.80, 0.84, 0.92, 200, ["anthem", "peak-time", "sing-along"]),
    _t("trk_excuses_ap", "Excuses", "AP Dhillon", "punjabi",
       ["desi_hiphop", "rnb"], ["romantic", "chill"], "2020s",
       90, 0.55, 0.74, 0.90, 175, ["sing-along", "late-night"]),
    _t("trk_summerhigh_ap", "Summer High", "AP Dhillon", "punjabi",
       ["desi_hiphop", "pop"], ["chill", "romantic"], "2020s",
       96, 0.60, 0.76, 0.82, 190, ["late-night", "cruise"]),
    _t("trk_insane_ap", "Insane", "AP Dhillon", "punjabi",
       ["desi_hiphop"], ["hype", "aggressive"], "2020s",
       100, 0.78, 0.82, 0.76, 185, ["peak-time", "swagger"]),
    _t("trk_withyou_ap", "With You", "AP Dhillon", "punjabi",
       ["desi_hiphop", "rnb"], ["romantic", "sensual"], "2020s",
       94, 0.54, 0.72, 0.74, 180, ["late-night", "slow-burn"]),
    _t("trk_admirin_ka", "Admirin' You", "Karan Aujla", "punjabi",
       ["desi_hiphop"], ["romantic", "celebratory"], "2020s",
       100, 0.72, 0.84, 0.86, 195, ["sing-along", "wedding"]),
    _t("trk_softly_ka", "Softly", "Karan Aujla", "punjabi",
       ["desi_hiphop", "pop"], ["romantic", "celebratory"], "2020s",
       104, 0.70, 0.86, 0.89, 175, ["sing-along", "viral", "wedding"]),
    _t("trk_dontlook_ka", "Don't Look", "Karan Aujla", "punjabi",
       ["desi_hiphop"], ["hype", "celebratory"], "2020s",
       95, 0.80, 0.84, 0.82, 190, ["peak-time", "swagger"]),
    _t("trk_mfgabhru_ka", "MF Gabhru!", "Karan Aujla", "punjabi",
       ["desi_hiphop", "bhangra"], ["hype", "aggressive"], "2020s",
       98, 0.85, 0.82, 0.74, 185, ["peak-time", "dhol"]),
    _t("trk_yaarjundee_ka", "Yaarian Ch Fikk", "Karan Aujla", "punjabi",
       ["desi_hiphop"], ["nostalgic", "chill"], "2020s",
       92, 0.58, 0.72, 0.70, 200, ["slow-burn", "late-night"]),
    _t("trk_295_sms", "295", "Sidhu Moose Wala", "punjabi",
       ["desi_hiphop"], ["nostalgic", "sad"], "2020s",
       90, 0.55, 0.62, 0.92, 240, ["sing-along", "tribute", "anthem"]),
    _t("trk_sohigh_sms", "So High", "Sidhu Moose Wala", "punjabi",
       ["desi_hiphop"], ["hype", "aggressive"], "2010s",
       96, 0.78, 0.78, 0.86, 215, ["peak-time", "swagger"]),
    _t("trk_lastride_sms", "The Last Ride", "Sidhu Moose Wala", "punjabi",
       ["desi_hiphop"], ["dark", "nostalgic"], "2020s",
       92, 0.68, 0.70, 0.82, 180, ["tribute", "sing-along"]),
    _t("trk_bambiha_sms", "Bambiha Bole", "Sidhu Moose Wala", "punjabi",
       ["desi_hiphop"], ["aggressive", "hype"], "2020s",
       94, 0.82, 0.78, 0.78, 210, ["peak-time", "swagger"]),
    _t("trk_elevated_sh", "Elevated", "Shubh", "punjabi",
       ["desi_hiphop"], ["chill", "hype"], "2020s",
       92, 0.70, 0.80, 0.86, 165, ["viral", "cruise"]),
    _t("trk_cheques_sh", "Cheques", "Shubh", "punjabi",
       ["desi_hiphop"], ["hype", "celebratory"], "2020s",
       96, 0.76, 0.84, 0.84, 180, ["peak-time", "swagger"]),
    _t("trk_werollin_sh", "We Rollin", "Shubh", "punjabi",
       ["desi_hiphop"], ["hype", "chill"], "2020s",
       94, 0.74, 0.82, 0.82, 170, ["cruise", "viral"]),
    _t("trk_challa_gm", "Challa", "Gurdas Maan", "punjabi",
       ["bhangra", "sufi"], ["nostalgic", "celebratory"], "1990s",
       132, 0.72, 0.76, 0.76, 300, ["dhol", "classic", "baraat"]),
    _t("trk_dildamamla_gm", "Dil Da Mamla", "Gurdas Maan", "punjabi",
       ["bhangra", "sufi"], ["nostalgic", "romantic"], "1980s",
       110, 0.55, 0.62, 0.62, 280, ["classic", "throwback"]),
    _t("trk_mundian_pmc", "Mundian To Bach Ke", "Panjabi MC", "punjabi",
       ["bhangra", "hiphop"], ["hype", "celebratory"], "2000s",
       105, 0.88, 0.92, 0.94, 250, ["dhol", "anthem", "peak-time", "baraat"]),
    _t("trk_jogi_pmc", "Jogi", "Panjabi MC", "punjabi",
       ["bhangra"], ["hype", "celebratory"], "2000s",
       140, 0.85, 0.88, 0.72, 240, ["dhol", "bhangra-floor", "baraat"]),
    _t("trk_angreji_yys", "Angreji Beat", "Yo Yo Honey Singh", "punjabi",
       ["desi_hiphop", "bhangra"], ["hype", "celebratory"], "2010s",
       130, 0.86, 0.90, 0.90, 220, ["anthem", "peak-time", "sing-along"]),
    _t("trk_brownrang_yys", "Brown Rang", "Yo Yo Honey Singh", "punjabi",
       ["desi_hiphop"], ["hype", "celebratory"], "2010s",
       128, 0.82, 0.88, 0.86, 235, ["peak-time", "throwback"]),
    _t("trk_blueeyes_yys", "Blue Eyes", "Yo Yo Honey Singh", "punjabi",
       ["desi_hiphop", "pop"], ["hype", "sensual"], "2010s",
       100, 0.80, 0.88, 0.86, 220, ["throwback", "sing-along"]),
    _t("trk_tunak_dm", "Tunak Tunak Tun", "Daler Mehndi", "punjabi",
       ["bhangra"], ["celebratory", "nostalgic"], "1990s",
       135, 0.90, 0.90, 0.90, 260, ["dhol", "baraat", "peak-time", "meme"]),
    _t("trk_bolotarara_dm", "Bolo Ta Ra Ra", "Daler Mehndi", "punjabi",
       ["bhangra"], ["celebratory", "hype"], "1990s",
       138, 0.88, 0.88, 0.74, 270, ["dhol", "bhangra-floor", "baraat"]),
    _t("trk_nachnu_sk", "Nachan Farrate", "Sukhbir", "punjabi",
       ["bhangra", "bollywood"], ["celebratory", "hype"], "2010s",
       128, 0.84, 0.90, 0.76, 230, ["dhol", "wedding", "sangeet"]),
    _t("trk_oyehoye_sk", "Oh Ho Ho Ho", "Sukhbir", "punjabi",
       ["bhangra"], ["celebratory", "hype"], "1990s",
       126, 0.85, 0.90, 0.80, 250, ["dhol", "throwback", "baraat"]),
    _t("trk_gtroad_ms", "Gur Nalo Ishq Mitha", "Malkit Singh", "punjabi",
       ["bhangra"], ["celebratory", "nostalgic"], "1990s",
       132, 0.86, 0.88, 0.78, 265, ["dhol", "classic", "baraat"]),
    _t("trk_mundeya_gr", "High Rated Gabru", "Guru Randhawa", "punjabi",
       ["bhangra", "pop"], ["hype", "celebratory"], "2010s",
       100, 0.80, 0.88, 0.85, 200, ["wedding", "sing-along"]),
    _t("trk_lahore_gr", "Lahore", "Guru Randhawa", "punjabi",
       ["bhangra", "pop"], ["romantic", "celebratory"], "2010s",
       96, 0.70, 0.84, 0.84, 195, ["wedding", "sing-along"]),
]


# ---------------------------------------------------------------------------
# Bollywood 1980s-2000s (the nostalgia engine)
# ---------------------------------------------------------------------------

_BOLLY_RETRO: List[Track] = [
    _t("trk_chaiyya", "Chaiyya Chaiyya", "Sukhwinder Singh & Sapna Awasthi", "hindi",
       ["bollywood", "sufi"], ["celebratory", "hype"], "1990s",
       128, 0.86, 0.86, 0.95, 400, ["classic", "sing-along", "srk", "peak-time"]),
    _t("trk_kajrare", "Kajra Re", "Alisha Chinai, Shankar Mahadevan & Javed Ali", "hindi",
       ["bollywood"], ["sensual", "celebratory"], "2000s",
       112, 0.78, 0.86, 0.92, 350, ["mujra", "sangeet", "classic"]),
    _t("trk_timetodisco", "It's The Time To Disco", "Shaan, KK & Vasundhara Das", "hindi",
       ["bollywood", "disco"], ["celebratory", "hype"], "2000s",
       128, 0.86, 0.88, 0.86, 300, ["throwback", "peak-time", "sing-along", "srk"]),
    _t("trk_dolare", "Dola Re Dola", "Shreya Ghoshal & Kavita Krishnamurthy", "hindi",
       ["bollywood"], ["celebratory", "hype"], "2000s",
       118, 0.82, 0.84, 0.90, 340, ["sangeet", "dance-number", "classic"]),
    _t("trk_bolechudiyan", "Bole Chudiyan", "Kavita Krishnamurthy & Udit Narayan", "hindi",
       ["bollywood"], ["celebratory", "romantic"], "2000s",
       130, 0.84, 0.90, 0.94, 380, ["sangeet", "wedding", "sing-along", "srk"]),
    _t("trk_ekpalkajeena", "Ek Pal Ka Jeena", "Lucky Ali", "hindi",
       ["bollywood", "pop"], ["hype", "nostalgic"], "2000s",
       122, 0.76, 0.82, 0.88, 280, ["hrithik", "throwback", "sing-along"]),
    _t("trk_dhoommachale", "Dhoom Machale", "Sunidhi Chauhan", "hindi",
       ["bollywood"], ["hype", "celebratory"], "2000s",
       124, 0.88, 0.90, 0.92, 260, ["peak-time", "throwback", "dance-number"]),
    _t("trk_kahonapyaar", "Kaho Naa Pyaar Hai", "Udit Narayan & Alka Yagnik", "hindi",
       ["bollywood"], ["romantic", "nostalgic"], "2000s",
       100, 0.55, 0.62, 0.86, 320, ["slow-burn", "hrithik", "sing-along"]),
    _t("trk_koimilgaya", "Koi Mil Gaya", "Udit Narayan & Alka Yagnik", "hindi",
       ["bollywood"], ["romantic", "celebratory"], "1990s",
       118, 0.72, 0.80, 0.86, 330, ["srk", "sangeet", "college"]),
    _t("trk_tujhedekhato", "Tujhe Dekha To", "Kumar Sanu & Lata Mangeshkar", "hindi",
       ["bollywood"], ["romantic", "nostalgic"], "1990s",
       92, 0.45, 0.52, 0.94, 300, ["ddlj", "srk", "sing-along", "slow-burn"]),
    _t("trk_pehlanasha", "Pehla Nasha", "Udit Narayan & Sadhana Sargam", "hindi",
       ["bollywood"], ["romantic", "nostalgic"], "1990s",
       88, 0.40, 0.46, 0.92, 290, ["slow-burn", "sing-along", "first-dance"]),
    _t("trk_churakedil", "Chura Ke Dil Mera", "Kumar Sanu & Alka Yagnik", "hindi",
       ["bollywood"], ["romantic", "celebratory"], "1990s",
       120, 0.74, 0.82, 0.84, 310, ["throwback", "dance-number", "akshay"]),
    _t("trk_ankhiyonse", "Ankhiyon Se Goli Maare", "Sonu Nigam & Jaspinder Narula", "hindi",
       ["bollywood"], ["celebratory", "hype"], "1990s",
       132, 0.86, 0.88, 0.82, 300, ["govinda", "dance-number", "peak-time"]),
    _t("trk_mobilenumber", "What Is Mobile Number", "Abhijeet & Alka Yagnik", "hindi",
       ["bollywood"], ["celebratory", "nostalgic"], "1990s",
       130, 0.82, 0.86, 0.72, 320, ["govinda", "throwback", "dance-number"]),
    _t("trk_gaddileke", "Main Nikla Gaddi Leke", "Udit Narayan", "hindi",
       ["bollywood"], ["celebratory", "nostalgic"], "2000s",
       122, 0.78, 0.80, 0.86, 340, ["sing-along", "road-trip", "throwback"]),
    _t("trk_kalhonaho", "Kal Ho Naa Ho", "Sonu Nigam", "hindi",
       ["bollywood"], ["romantic", "sad"], "2000s",
       88, 0.38, 0.42, 0.94, 320, ["srk", "closer", "sing-along", "slow-burn"]),
    _t("trk_maahive", "Maahi Ve", "Sonu Nigam & Sunidhi Chauhan", "hindi",
       ["bollywood"], ["celebratory", "romantic"], "2000s",
       128, 0.80, 0.86, 0.87, 330, ["sangeet", "wedding", "srk"]),
    _t("trk_desigirl", "Desi Girl", "Sunidhi Chauhan & Vishal Dadlani", "hindi",
       ["bollywood"], ["celebratory", "hype"], "2000s",
       124, 0.85, 0.88, 0.89, 270, ["dance-number", "peak-time", "sangeet"]),
    _t("trk_omshantiom80", "Om Shanti Om", "Kishore Kumar", "hindi",
       ["bollywood", "disco"], ["celebratory", "nostalgic"], "1980s",
       126, 0.82, 0.86, 0.86, 300, ["retro", "throwback", "classic"]),
    _t("trk_jimmyjimmy", "Jimmy Jimmy Aaja", "Parvati Khan", "hindi",
       ["bollywood", "disco"], ["celebratory", "nostalgic"], "1980s",
       120, 0.80, 0.88, 0.82, 300, ["retro", "throwback"]),
    _t("trk_discodancer", "I Am A Disco Dancer", "Vijay Benedict", "hindi",
       ["bollywood", "disco"], ["hype", "celebratory"], "1980s",
       124, 0.86, 0.90, 0.86, 290, ["retro", "peak-time", "throwback"]),
    _t("trk_ekdoteen", "Ek Do Teen", "Alka Yagnik", "hindi",
       ["bollywood"], ["celebratory", "hype"], "1980s",
       128, 0.85, 0.88, 0.86, 300, ["dance-number", "retro", "madhuri"]),
    _t("trk_cholike", "Choli Ke Peeche", "Ila Arun & Alka Yagnik", "hindi",
       ["bollywood"], ["celebratory", "sensual"], "1990s",
       126, 0.82, 0.86, 0.86, 330, ["dance-number", "madhuri", "throwback"]),
    _t("trk_dideradevar", "Didi Tera Devar Deewana", "Lata Mangeshkar & S. P. Balasubrahmanyam", "hindi",
       ["bollywood"], ["celebratory", "nostalgic"], "1990s",
       116, 0.72, 0.80, 0.88, 340, ["sangeet", "wedding", "classic", "madhuri"]),
    _t("trk_shavashava", "Say Shava Shava", "Amitabh Bachchan & Alka Yagnik", "hindi",
       ["bollywood", "bhangra"], ["celebratory", "hype"], "2000s",
       128, 0.85, 0.88, 0.88, 350, ["sangeet", "wedding", "dhol", "srk"]),
    _t("trk_mahiveka", "Mahi Ve", "Udit Narayan & Sunidhi Chauhan", "hindi",
       ["bollywood"], ["celebratory", "romantic"], "2000s",
       126, 0.80, 0.86, 0.84, 320, ["sangeet", "wedding", "dhol"]),
    _t("trk_yehkaali", "Yeh Kaali Kaali Aankhein", "Kumar Sanu & Udit Narayan", "hindi",
       ["bollywood"], ["celebratory", "sensual"], "1990s",
       124, 0.80, 0.84, 0.88, 330, ["srk", "throwback", "dance-number"]),
    _t("trk_dilse_re", "Dil Se Re", "A. R. Rahman", "hindi",
       ["bollywood", "sufi"], ["nostalgic", "romantic"], "1990s",
       104, 0.62, 0.60, 0.80, 400, ["classic", "rahman"]),
    _t("trk_kabhialvida", "Kabhi Alvida Naa Kehna", "Sonu Nigam, Alka Yagnik & Shafqat Amanat Ali", "hindi",
       ["bollywood"], ["sad", "romantic"], "2000s",
       90, 0.38, 0.40, 0.85, 350, ["closer", "slow-burn", "srk"]),
    _t("trk_sharara", "Sharara Sharara", "Asha Bhosle", "hindi",
       ["bollywood"], ["celebratory", "sensual"], "2000s",
       126, 0.82, 0.86, 0.80, 310, ["dance-number", "throwback"]),
]


# ---------------------------------------------------------------------------
# Bollywood 2010s-2020s
# ---------------------------------------------------------------------------

_BOLLY_MODERN: List[Track] = [
    _t("trk_kalachashma", "Kala Chashma", "Amar Arshi, Badshah & Neha Kakkar", "hindi",
       ["bollywood", "bhangra"], ["hype", "celebratory"], "2010s",
       105, 0.90, 0.92, 0.96, 220, ["peak-time", "anthem", "wedding", "sing-along"]),
    _t("trk_gallangoodiyaan", "Gallan Goodiyaan", "Various Artists", "hindi",
       ["bollywood"], ["celebratory", "hype"], "2010s",
       128, 0.88, 0.90, 0.92, 300, ["sangeet", "wedding", "dhol", "sing-along"]),
    _t("trk_badtameezdil", "Badtameez Dil", "Benny Dayal", "hindi",
       ["bollywood"], ["hype", "celebratory"], "2010s",
       130, 0.87, 0.88, 0.91, 260, ["peak-time", "ranbir", "college"]),
    _t("trk_londonthumakda", "London Thumakda", "Labh Janjua, Sonu Kakkar & Neha Kakkar", "hindi",
       ["bollywood", "bhangra"], ["celebratory", "hype"], "2010s",
       132, 0.85, 0.88, 0.89, 200, ["baraat", "wedding", "dhol"]),
    _t("trk_balampichkari", "Balam Pichkari", "Vishal Dadlani & Shalmali Kholgade", "hindi",
       ["bollywood"], ["celebratory", "hype"], "2010s",
       130, 0.86, 0.90, 0.91, 280, ["holi", "sangeet", "peak-time"]),
    _t("trk_malhari", "Malhari", "Vishal Dadlani", "hindi",
       ["bollywood"], ["hype", "aggressive"], "2010s",
       140, 0.92, 0.84, 0.86, 210, ["dhol", "baraat", "peak-time"]),
    _t("trk_ghungroo", "Ghungroo", "Arijit Singh & Shilpa Rao", "hindi",
       ["bollywood"], ["celebratory", "romantic"], "2010s",
       116, 0.80, 0.86, 0.86, 300, ["wedding", "sangeet", "hrithik"]),
    _t("trk_nashesi", "Nashe Si Chadh Gayi", "Arijit Singh", "hindi",
       ["bollywood"], ["hype", "celebratory"], "2010s",
       132, 0.86, 0.88, 0.90, 240, ["peak-time", "sing-along"]),
    _t("trk_kargayichull", "Kar Gayi Chull", "Badshah, Neha Kakkar & Fazilpuria", "hindi",
       ["bollywood", "desi_hiphop"], ["hype", "celebratory"], "2010s",
       100, 0.85, 0.90, 0.89, 200, ["peak-time", "party", "college"]),
    _t("trk_saudakhara", "Sauda Khara Khara", "Sukhbir, Diljit Dosanjh & Dhvani Bhanushali", "hindi",
       ["bollywood", "bhangra"], ["celebratory", "hype"], "2010s",
       100, 0.86, 0.90, 0.83, 220, ["baraat", "dhol", "wedding"]),
    _t("trk_nagadasangdhol", "Nagada Sang Dhol", "Shreya Ghoshal & Osman Mir", "hindi",
       ["bollywood"], ["celebratory", "hype"], "2010s",
       130, 0.88, 0.88, 0.86, 290, ["dhol", "garba", "sangeet"]),
    _t("trk_aankhmarey", "Aankh Marey", "Neha Kakkar, Mika Singh & Kumar Sanu", "hindi",
       ["bollywood"], ["celebratory", "hype"], "2010s",
       118, 0.83, 0.89, 0.87, 210, ["sangeet", "throwback", "sing-along"]),
    _t("trk_lungidance", "Lungi Dance", "Yo Yo Honey Singh", "hindi",
       ["bollywood", "desi_hiphop"], ["celebratory", "hype"], "2010s",
       100, 0.85, 0.88, 0.89, 220, ["peak-time", "meme", "sing-along"]),
    _t("trk_saturday", "Saturday Saturday", "Badshah & Indeep Bakshi", "hindi",
       ["bollywood", "desi_hiphop"], ["hype", "celebratory"], "2010s",
       122, 0.82, 0.88, 0.80, 200, ["party", "college"]),
    _t("trk_djwalebabu", "DJ Waley Babu", "Badshah & Aastha Gill", "hindi",
       ["desi_hiphop", "hiphop"], ["hype", "celebratory"], "2010s",
       100, 0.86, 0.88, 0.86, 210, ["peak-time", "anthem", "party"]),
    _t("trk_gendaphool", "Genda Phool", "Badshah & Payal Dev", "hindi",
       ["desi_hiphop", "pop"], ["celebratory", "hype"], "2020s",
       100, 0.80, 0.88, 0.82, 165, ["party", "viral"]),
    _t("trk_gullymein", "Mere Gully Mein", "DIVINE & Naezy", "hindi",
       ["desi_hiphop", "hiphop"], ["aggressive", "hype"], "2010s",
       92, 0.78, 0.76, 0.80, 230, ["gully", "mumbai"]),
    _t("trk_apnatime", "Apna Time Aayega", "DIVINE", "hindi",
       ["desi_hiphop", "hiphop"], ["hype", "aggressive"], "2010s",
       88, 0.82, 0.74, 0.89, 200, ["anthem", "gully", "sing-along"]),
    _t("trk_kohinoor", "Kohinoor", "DIVINE", "hindi",
       ["desi_hiphop", "hiphop"], ["aggressive", "dark"], "2010s",
       94, 0.80, 0.78, 0.72, 215, ["gully", "peak-time"]),
    _t("trk_tumhiho", "Tum Hi Ho", "Arijit Singh", "hindi",
       ["bollywood"], ["romantic", "sad"], "2010s",
       76, 0.30, 0.36, 0.96, 260, ["slow-burn", "closer", "sing-along"]),
    _t("trk_channamereya", "Channa Mereya", "Arijit Singh", "hindi",
       ["bollywood"], ["sad", "romantic"], "2010s",
       90, 0.40, 0.42, 0.93, 290, ["slow-burn", "sing-along", "heartbreak"]),
    _t("trk_kesariya", "Kesariya", "Arijit Singh", "hindi",
       ["bollywood"], ["romantic", "nostalgic"], "2020s",
       96, 0.50, 0.56, 0.93, 270, ["sing-along", "wedding", "first-dance"]),
    _t("trk_raabta", "Raabta", "Arijit Singh", "hindi",
       ["bollywood"], ["romantic"], "2010s",
       100, 0.50, 0.60, 0.86, 240, ["slow-burn", "first-dance"]),
    _t("trk_ilahi", "Ilahi", "Arijit Singh", "hindi",
       ["bollywood"], ["chill", "nostalgic"], "2010s",
       118, 0.55, 0.62, 0.85, 220, ["road-trip", "sing-along"]),
    _t("trk_chaleya", "Chaleya", "Arijit Singh & Shilpa Rao", "hindi",
       ["bollywood"], ["romantic", "celebratory"], "2020s",
       105, 0.62, 0.78, 0.86, 220, ["wedding", "sing-along", "srk"]),
    _t("trk_jhoomejopathaan", "Jhoome Jo Pathaan", "Arijit Singh & Sukriti Kakar", "hindi",
       ["bollywood"], ["hype", "celebratory"], "2020s",
       122, 0.86, 0.88, 0.86, 210, ["srk", "peak-time", "dance-number"]),
    _t("trk_whatjhumka", "What Jhumka?", "Arijit Singh & Jonita Gandhi", "hindi",
       ["bollywood"], ["celebratory", "hype"], "2020s",
       118, 0.80, 0.86, 0.78, 210, ["sangeet", "wedding"]),
    _t("trk_naachmerirani", "Naach Meri Rani", "Guru Randhawa & Nikhita Gandhi", "hindi",
       ["pop", "bollywood"], ["celebratory", "sensual"], "2020s",
       98, 0.78, 0.86, 0.80, 200, ["party", "sangeet"]),
    _t("trk_makhna", "Makhna", "Tanishk Bagchi, Yasser Desai & Asees Kaur", "hindi",
       ["bollywood"], ["celebratory", "sensual"], "2010s",
       104, 0.78, 0.86, 0.78, 200, ["party", "dance-number"]),
    _t("trk_seetimaar", "Coca Cola", "Tony Kakkar & Neha Kakkar", "hindi",
       ["pop", "bollywood"], ["celebratory", "hype"], "2010s",
       102, 0.78, 0.88, 0.76, 195, ["party", "viral"]),
    _t("trk_zingaat", "Zingaat", "Ajay-Atul", "hindi",
       ["bollywood"], ["hype", "celebratory"], "2010s",
       140, 0.92, 0.88, 0.84, 210, ["dhol", "baraat", "peak-time"]),
    _t("trk_afghanjalebi", "Afghan Jalebi", "Asrar", "hindi",
       ["bollywood", "sufi"], ["dark", "sensual"], "2010s",
       108, 0.72, 0.78, 0.78, 250, ["late-night", "dance-number"]),
]


# ---------------------------------------------------------------------------
# South Indian + Arabic crossover
# ---------------------------------------------------------------------------

_REGIONAL: List[Track] = [
    _t("trk_naatunaatu", "Naatu Naatu", "Rahul Sipligunj & Kaala Bhairava", "telugu",
       ["bollywood"], ["hype", "celebratory"], "2020s",
       140, 0.95, 0.90, 0.94, 275, ["peak-time", "anthem", "dance-number"]),
    _t("trk_ooantava", "Oo Antava", "Indravathi Chauhan", "telugu",
       ["bollywood"], ["sensual", "hype"], "2020s",
       128, 0.85, 0.88, 0.86, 240, ["dance-number", "peak-time"]),
    _t("trk_rowdybaby", "Rowdy Baby", "Dhanush & Dhee", "tamil",
       ["bollywood"], ["celebratory", "hype"], "2010s",
       130, 0.88, 0.90, 0.88, 250, ["dance-number", "peak-time"]),
    _t("trk_arabickuthu", "Arabic Kuthu", "Anirudh Ravichander & Jonita Gandhi", "tamil",
       ["bollywood"], ["hype", "celebratory"], "2020s",
       145, 0.92, 0.90, 0.87, 245, ["peak-time", "dance-number", "dhol"]),
    _t("trk_kolaveri", "Why This Kolaveri Di", "Dhanush", "tamil",
       ["bollywood", "pop"], ["nostalgic", "chill"], "2010s",
       108, 0.55, 0.70, 0.88, 250, ["meme", "sing-along", "throwback"]),
    _t("trk_3daqat", "3 Daqat", "Abu & Yousra", "arabic",
       ["pop"], ["romantic", "celebratory"], "2010s",
       100, 0.68, 0.82, 0.72, 240, ["shaabi", "wedding"]),
    _t("trk_entaeih", "Enta Eih", "Nancy Ajram", "arabic",
       ["pop"], ["romantic", "sad"], "2000s",
       100, 0.50, 0.66, 0.70, 260, ["slow-burn"]),
]


# ---------------------------------------------------------------------------
# Western hip-hop / R&B
# ---------------------------------------------------------------------------

_HIPHOP_RNB: List[Track] = [
    _t("trk_godsplan_dr", "God's Plan", "Drake", "english",
       ["hiphop"], ["hype", "dark"], "2010s",
       77, 0.70, 0.76, 0.96, 199, ["sing-along", "anthem", "half-time"]),
    _t("trk_onedance_dr", "One Dance", "Drake", "english",
       ["hiphop", "afrobeat"], ["hype", "sensual"], "2010s",
       104, 0.76, 0.90, 0.96, 173, ["crossover", "peak-time", "sing-along"]),
    _t("trk_passionfruit_dr", "Passionfruit", "Drake", "english",
       ["rnb", "house"], ["chill", "sensual"], "2010s",
       112, 0.56, 0.86, 0.86, 298, ["late-night", "smooth"]),
    _t("trk_nonstop_dr", "Nonstop", "Drake", "english",
       ["hiphop"], ["aggressive", "hype"], "2010s",
       154, 0.80, 0.80, 0.86, 238, ["peak-time", "half-time"]),
    _t("trk_sickomode_ts", "SICKO MODE", "Travis Scott", "english",
       ["hiphop"], ["dark", "hype"], "2010s",
       155, 0.86, 0.83, 0.95, 313, ["peak-time", "anthem"]),
    _t("trk_goosebumps_ts", "goosebumps", "Travis Scott", "english",
       ["hiphop"], ["dark", "hype"], "2010s",
       130, 0.80, 0.84, 0.92, 243, ["peak-time", "sing-along"]),
    _t("trk_fein_ts", "FE!N", "Travis Scott", "english",
       ["hiphop"], ["aggressive", "dark"], "2020s",
       148, 0.92, 0.80, 0.86, 191, ["peak-time", "mosh"]),
    _t("trk_humble_kl", "HUMBLE.", "Kendrick Lamar", "english",
       ["hiphop"], ["aggressive", "hype"], "2010s",
       150, 0.86, 0.90, 0.95, 177, ["anthem", "sing-along", "peak-time"]),
    _t("trk_dna_kl", "DNA.", "Kendrick Lamar", "english",
       ["hiphop"], ["aggressive", "dark"], "2010s",
       140, 0.88, 0.80, 0.86, 186, ["peak-time", "mosh"]),
    _t("trk_notlikeus_kl", "Not Like Us", "Kendrick Lamar", "english",
       ["hiphop"], ["aggressive", "celebratory"], "2020s",
       101, 0.88, 0.92, 0.96, 274, ["anthem", "sing-along", "peak-time"]),
    _t("trk_bodakyellow_cb", "Bodak Yellow", "Cardi B", "english",
       ["hiphop"], ["aggressive", "hype"], "2010s",
       125, 0.82, 0.86, 0.90, 224, ["peak-time", "anthem"]),
    _t("trk_wap_cb", "WAP", "Cardi B & Megan Thee Stallion", "english",
       ["hiphop"], ["sensual", "aggressive"], "2020s",
       133, 0.86, 0.94, 0.88, 187, ["peak-time", "twerk"]),
    _t("trk_ilikeit_cb", "I Like It", "Cardi B, Bad Bunny & J Balvin", "english",
       ["hiphop", "reggaeton"], ["hype", "celebratory"], "2010s",
       136, 0.88, 0.86, 0.93, 253, ["crossover", "peak-time", "sing-along"]),
    _t("trk_sayso_dc", "Say So", "Doja Cat", "english",
       ["pop", "disco", "rnb"], ["sensual", "celebratory"], "2020s",
       111, 0.72, 0.90, 0.93, 238, ["viral", "sing-along"]),
    _t("trk_woman_dc", "Woman", "Doja Cat", "english",
       ["rnb", "afrobeat"], ["sensual", "celebratory"], "2020s",
       108, 0.72, 0.88, 0.86, 173, ["smooth", "peak-time"]),
    _t("trk_painttown_dc", "Paint The Town Red", "Doja Cat", "english",
       ["hiphop", "pop"], ["dark", "celebratory"], "2020s",
       100, 0.76, 0.88, 0.89, 231, ["viral", "sing-along"]),
    _t("trk_blindinglights_tw", "Blinding Lights", "The Weeknd", "english",
       ["pop", "disco"], ["euphoric", "nostalgic"], "2020s",
       171, 0.86, 0.80, 0.98, 200, ["anthem", "sing-along", "peak-time"]),
    _t("trk_starboy_tw", "Starboy", "The Weeknd & Daft Punk", "english",
       ["rnb", "pop"], ["dark", "sensual"], "2010s",
       186, 0.72, 0.68, 0.93, 230, ["late-night", "sing-along"]),
    _t("trk_cantfeelface_tw", "Can't Feel My Face", "The Weeknd", "english",
       ["pop", "disco"], ["celebratory", "euphoric"], "2010s",
       108, 0.76, 0.88, 0.93, 213, ["sing-along", "throwback"]),
    _t("trk_killbill_sza", "Kill Bill", "SZA", "english",
       ["rnb"], ["dark", "chill"], "2020s",
       89, 0.55, 0.78, 0.93, 154, ["sing-along", "late-night"]),
    _t("trk_gooddays_sza", "Good Days", "SZA", "english",
       ["rnb"], ["chill", "romantic"], "2020s",
       122, 0.45, 0.66, 0.83, 279, ["late-night", "smooth"]),
    _t("trk_snooze_sza", "Snooze", "SZA", "english",
       ["rnb"], ["sensual", "chill"], "2020s",
       143, 0.50, 0.70, 0.86, 201, ["late-night", "smooth"]),
    _t("trk_umbrella_ri", "Umbrella", "Rihanna & JAY-Z", "english",
       ["pop", "rnb"], ["nostalgic", "celebratory"], "2000s",
       174, 0.80, 0.60, 0.97, 263, ["sing-along", "throwback"]),
    _t("trk_wefoundlove_ri", "We Found Love", "Rihanna & Calvin Harris", "english",
       ["edm", "pop"], ["euphoric", "hype"], "2010s",
       128, 0.90, 0.74, 0.96, 215, ["peak-time", "sing-along", "anthem"]),
    _t("trk_work_ri", "Work", "Rihanna & Drake", "english",
       ["rnb", "afrobeat"], ["sensual", "chill"], "2010s",
       92, 0.62, 0.90, 0.91, 219, ["late-night", "wine"]),
    _t("trk_crazyinlove_be", "Crazy In Love", "Beyonce & JAY-Z", "english",
       ["rnb", "pop"], ["hype", "celebratory"], "2000s",
       99, 0.86, 0.78, 0.96, 236, ["throwback", "sing-along", "peak-time"]),
    _t("trk_singleladies_be", "Single Ladies", "Beyonce", "english",
       ["rnb", "pop"], ["celebratory", "hype"], "2000s",
       193, 0.86, 0.72, 0.96, 193, ["sing-along", "throwback", "wedding"]),
    _t("trk_cuffit_be", "CUFF IT", "Beyonce", "english",
       ["disco", "rnb"], ["celebratory", "euphoric"], "2020s",
       115, 0.82, 0.90, 0.91, 225, ["peak-time", "sing-along", "wedding"]),
    _t("trk_yeah_us", "Yeah!", "Usher, Lil Jon & Ludacris", "english",
       ["rnb", "hiphop"], ["hype", "celebratory"], "2000s",
       105, 0.90, 0.90, 0.97, 250, ["throwback", "peak-time", "sing-along"]),
    _t("trk_inda_club", "In Da Club", "50 Cent", "english",
       ["hiphop"], ["hype", "celebratory"], "2000s",
       90, 0.82, 0.90, 0.95, 233, ["throwback", "birthday", "sing-along"]),
]


# ---------------------------------------------------------------------------
# House / techno / EDM
# ---------------------------------------------------------------------------

_DANCE: List[Track] = [
    _t("trk_turnonlights_fa", "Turn On The Lights again..", "Fred again.. & Swedish House Mafia", "english",
       ["house"], ["euphoric", "hype"], "2020s",
       130, 0.88, 0.86, 0.86, 210, ["peak-time", "festival"]),
    _t("trk_rumble_fa", "Rumble", "Fred again.., Skrillex & Flowdan", "english",
       ["house", "garage"], ["dark", "aggressive"], "2020s",
       140, 0.90, 0.82, 0.82, 208, ["peak-time", "festival"]),
    _t("trk_delilah_fa", "Delilah (pull me out of this)", "Fred again..", "english",
       ["house"], ["euphoric", "hype"], "2020s",
       132, 0.86, 0.84, 0.82, 217, ["peak-time", "emotional"]),
    _t("trk_marea_fa", "Marea (we've lost dancing)", "Fred again..", "english",
       ["house"], ["euphoric", "nostalgic"], "2020s",
       128, 0.80, 0.82, 0.78, 271, ["emotional", "closer"]),
    _t("trk_itgoeslike_pg", "(It Goes Like) Nanana", "Peggy Gou", "english",
       ["house"], ["euphoric", "celebratory"], "2020s",
       124, 0.82, 0.90, 0.86, 200, ["sing-along", "peak-time"]),
    _t("trk_starrynight_pg", "Starry Night", "Peggy Gou", "english",
       ["house"], ["euphoric", "chill"], "2010s",
       122, 0.76, 0.86, 0.72, 260, ["sunset", "groove"]),
    _t("trk_onemoretime_dp", "One More Time", "Daft Punk", "english",
       ["house", "disco"], ["euphoric", "celebratory"], "2000s",
       123, 0.90, 0.88, 0.97, 320, ["anthem", "peak-time", "sing-along"]),
    _t("trk_getlucky_dp", "Get Lucky", "Daft Punk & Pharrell Williams", "english",
       ["disco", "house"], ["celebratory", "euphoric"], "2010s",
       116, 0.76, 0.90, 0.95, 248, ["sing-along", "groove"]),
    _t("trk_onekiss_ch", "One Kiss", "Calvin Harris & Dua Lipa", "english",
       ["house", "pop"], ["euphoric", "celebratory"], "2010s",
       124, 0.82, 0.90, 0.96, 214, ["sing-along", "peak-time"]),
    _t("trk_summer_ch", "Summer", "Calvin Harris", "english",
       ["edm", "house"], ["euphoric", "hype"], "2010s",
       128, 0.88, 0.82, 0.91, 223, ["festival", "peak-time"]),
    _t("trk_feelsoclose_ch", "Feel So Close", "Calvin Harris", "english",
       ["house", "edm"], ["euphoric", "celebratory"], "2010s",
       128, 0.86, 0.86, 0.89, 205, ["sing-along", "festival"]),
    _t("trk_dontyouworry_shm", "Don't You Worry Child", "Swedish House Mafia", "english",
       ["edm", "house"], ["euphoric", "nostalgic"], "2010s",
       129, 0.90, 0.76, 0.95, 213, ["anthem", "sing-along", "peak-time"]),
    _t("trk_greyhound_shm", "Greyhound", "Swedish House Mafia", "english",
       ["edm", "house"], ["hype", "euphoric"], "2010s",
       126, 0.90, 0.82, 0.74, 220, ["festival", "peak-time"]),
    _t("trk_titanium_dg", "Titanium", "David Guetta & Sia", "english",
       ["edm", "pop"], ["euphoric", "hype"], "2010s",
       126, 0.88, 0.72, 0.96, 245, ["sing-along", "anthem"]),
    _t("trk_sexychick_dg", "Sexy Chick", "David Guetta & Akon", "english",
       ["edm", "house"], ["celebratory", "hype"], "2000s",
       130, 0.86, 0.86, 0.89, 194, ["throwback", "peak-time"]),
    _t("trk_imgood_dg", "I'm Good (Blue)", "David Guetta & Bebe Rexha", "english",
       ["edm", "pop"], ["euphoric", "celebratory"], "2020s",
       128, 0.90, 0.86, 0.93, 175, ["peak-time", "sing-along"]),
    _t("trk_losingit_fi", "Losing It", "FISHER", "english",
       ["techno", "house"], ["hype", "euphoric"], "2010s",
       125, 0.90, 0.86, 0.86, 235, ["peak-time", "festival"]),
    _t("trk_takeitoff_fi", "Take It Off", "FISHER", "english",
       ["house", "techno"], ["hype", "euphoric"], "2020s",
       128, 0.90, 0.86, 0.76, 210, ["peak-time", "festival"]),
    _t("trk_turnoffthelights_cl", "Turn Off The Lights", "Chris Lake & Alexander Technique", "english",
       ["house", "techno"], ["dark", "sensual"], "2020s",
       128, 0.86, 0.88, 0.76, 220, ["peak-time", "late-night"]),
    _t("trk_deceiver_cl", "Deceiver", "Chris Lake & Green Velvet", "english",
       ["house", "techno"], ["dark", "hype"], "2020s",
       126, 0.86, 0.86, 0.66, 240, ["peak-time", "late-night"]),
    _t("trk_glue_bi", "Glue", "Bicep", "english",
       ["house", "techno"], ["euphoric", "nostalgic"], "2010s",
       130, 0.76, 0.78, 0.72, 322, ["emotional", "closer"]),
    _t("trk_apricots_bi", "Apricots", "Bicep", "english",
       ["house", "techno"], ["euphoric", "chill"], "2020s",
       128, 0.78, 0.80, 0.66, 290, ["groove", "sunset"]),
    _t("trk_levels_av", "Levels", "Avicii", "english",
       ["edm", "house"], ["euphoric", "hype"], "2010s",
       126, 0.92, 0.80, 0.96, 202, ["anthem", "peak-time", "festival"]),
    _t("trk_wakemeup_av", "Wake Me Up", "Avicii", "english",
       ["edm", "pop"], ["euphoric", "nostalgic"], "2010s",
       124, 0.80, 0.78, 0.96, 249, ["sing-along", "festival"]),
    _t("trk_animals_mg", "Animals", "Martin Garrix", "english",
       ["edm"], ["hype", "aggressive"], "2010s",
       128, 0.95, 0.76, 0.91, 185, ["peak-time", "festival", "drop"]),
    _t("trk_beforeiforget", "Miss You", "Oliver Tree & Robin Schulz", "english",
       ["edm", "house"], ["euphoric", "sad"], "2020s",
       126, 0.84, 0.84, 0.84, 165, ["sing-along", "peak-time"]),
    _t("trk_padam_ky", "Padam Padam", "Kylie Minogue", "english",
       ["pop", "house"], ["celebratory", "euphoric"], "2020s",
       122, 0.82, 0.88, 0.85, 171, ["viral", "sing-along", "peak-time"]),
    _t("trk_bodyfunction_bd", "Body Funktion", "Kettama", "english",
       ["techno", "house"], ["hype", "euphoric"], "2020s",
       134, 0.90, 0.84, 0.60, 290, ["peak-time", "rave"]),
]


# ---------------------------------------------------------------------------
# Retro / disco / pop anthems
# ---------------------------------------------------------------------------

_RETRO: List[Track] = [
    _t("trk_dancingqueen_ab", "Dancing Queen", "ABBA", "english",
       ["disco", "pop"], ["celebratory", "nostalgic"], "1980s",
       101, 0.72, 0.82, 0.97, 231, ["wedding", "sing-along", "classic"]),
    _t("trk_gimme_ab", "Gimme! Gimme! Gimme!", "ABBA", "english",
       ["disco", "pop"], ["nostalgic", "celebratory"], "1980s",
       118, 0.80, 0.86, 0.86, 292, ["throwback", "sing-along"]),
    _t("trk_mammamia_ab", "Mamma Mia", "ABBA", "english",
       ["disco", "pop"], ["celebratory", "nostalgic"], "1980s",
       138, 0.80, 0.80, 0.92, 213, ["sing-along", "wedding"]),
    _t("trk_billiejean_mj", "Billie Jean", "Michael Jackson", "english",
       ["pop", "disco"], ["nostalgic", "sensual"], "1980s",
       117, 0.80, 0.92, 0.98, 294, ["classic", "sing-along", "peak-time"]),
    _t("trk_thriller_mj", "Thriller", "Michael Jackson", "english",
       ["pop", "disco"], ["celebratory", "nostalgic"], "1980s",
       118, 0.80, 0.88, 0.97, 357, ["classic", "halloween", "sing-along"]),
    _t("trk_dontstoptil_mj", "Don't Stop 'Til You Get Enough", "Michael Jackson", "english",
       ["disco"], ["euphoric", "celebratory"], "1980s",
       119, 0.86, 0.92, 0.90, 366, ["groove", "peak-time"]),
    _t("trk_beatit_mj", "Beat It", "Michael Jackson", "english",
       ["rock", "pop"], ["hype", "nostalgic"], "1980s",
       139, 0.86, 0.72, 0.95, 258, ["sing-along", "classic"]),
    _t("trk_dontstopmenow_qu", "Don't Stop Me Now", "Queen", "english",
       ["rock", "pop"], ["euphoric", "celebratory"], "1980s",
       156, 0.90, 0.62, 0.96, 209, ["sing-along", "closer"]),
    _t("trk_bohemian_qu", "Bohemian Rhapsody", "Queen", "english",
       ["rock"], ["nostalgic", "euphoric"], "1980s",
       144, 0.62, 0.42, 0.98, 355, ["sing-along", "closer"]),
    _t("trk_wewillrockyou_qu", "We Will Rock You", "Queen", "english",
       ["rock"], ["hype", "celebratory"], "1980s",
       81, 0.72, 0.52, 0.97, 122, ["sing-along", "stomp", "half-time"]),
    _t("trk_wannadance_wh", "I Wanna Dance with Somebody", "Whitney Houston", "english",
       ["pop", "disco"], ["euphoric", "celebratory"], "1980s",
       119, 0.90, 0.86, 0.97, 291, ["sing-along", "peak-time", "wedding"]),
    _t("trk_alwaysloveyou_wh", "I Will Always Love You", "Whitney Houston", "english",
       ["pop"], ["sad", "romantic"], "1990s",
       134, 0.40, 0.32, 0.97, 273, ["closer", "sing-along", "first-dance"]),
    _t("trk_september_ewf", "September", "Earth, Wind & Fire", "english",
       ["disco"], ["celebratory", "euphoric"], "1980s",
       126, 0.86, 0.90, 0.96, 215, ["wedding", "sing-along", "peak-time"]),
    _t("trk_boogiewonder_ewf", "Boogie Wonderland", "Earth, Wind & Fire", "english",
       ["disco"], ["celebratory", "euphoric"], "1980s",
       130, 0.86, 0.88, 0.86, 285, ["wedding", "groove"]),
    _t("trk_stayinalive_bg", "Stayin' Alive", "Bee Gees", "english",
       ["disco"], ["celebratory", "nostalgic"], "1980s",
       104, 0.76, 0.90, 0.96, 285, ["classic", "sing-along"]),
    _t("trk_nightfever_bg", "Night Fever", "Bee Gees", "english",
       ["disco"], ["sensual", "nostalgic"], "1980s",
       109, 0.70, 0.90, 0.86, 208, ["groove", "throwback"]),
    _t("trk_mrbrightside_ki", "Mr. Brightside", "The Killers", "english",
       ["rock"], ["euphoric", "nostalgic"], "2000s",
       148, 0.90, 0.62, 0.96, 222, ["sing-along", "closer", "indie"]),
    _t("trk_levitating_dl", "Levitating", "Dua Lipa", "english",
       ["disco", "pop"], ["euphoric", "celebratory"], "2020s",
       103, 0.80, 0.88, 0.95, 203, ["sing-along", "groove"]),
    _t("trk_dontstartnow_dl", "Don't Start Now", "Dua Lipa", "english",
       ["disco", "pop"], ["celebratory", "euphoric"], "2020s",
       124, 0.82, 0.90, 0.96, 183, ["peak-time", "sing-along"]),
    _t("trk_uptownfunk_mr", "Uptown Funk", "Mark Ronson & Bruno Mars", "english",
       ["disco", "pop"], ["celebratory", "hype"], "2010s",
       115, 0.90, 0.90, 0.98, 270, ["wedding", "sing-along", "peak-time"]),
    _t("trk_24kmagic_bm", "24K Magic", "Bruno Mars", "english",
       ["rnb", "disco"], ["celebratory", "hype"], "2010s",
       107, 0.84, 0.90, 0.94, 226, ["wedding", "sing-along"]),
    _t("trk_sweetcaroline_nd", "Sweet Caroline", "Neil Diamond", "english",
       ["pop", "rock"], ["nostalgic", "celebratory"], "1980s",
       126, 0.66, 0.56, 0.94, 201, ["sing-along", "closer", "crowd"]),
    _t("trk_sweetchild_gr", "Sweet Child O' Mine", "Guns N' Roses", "english",
       ["rock"], ["nostalgic", "hype"], "1980s",
       125, 0.86, 0.56, 0.95, 356, ["sing-along", "classic"]),
    _t("trk_livinonaprayer_bj", "Livin' On A Prayer", "Bon Jovi", "english",
       ["rock", "pop"], ["euphoric", "nostalgic"], "1980s",
       123, 0.88, 0.58, 0.95, 249, ["sing-along", "closer"]),
]


# ---------------------------------------------------------------------------
# Reggaeton / Latin
# ---------------------------------------------------------------------------

_LATIN: List[Track] = [
    _t("trk_despacito_lf", "Despacito", "Luis Fonsi & Daddy Yankee", "spanish",
       ["reggaeton", "pop"], ["sensual", "celebratory"], "2010s",
       89, 0.80, 0.90, 0.98, 229, ["sing-along", "crossover"]),
    _t("trk_gasolina_dy", "Gasolina", "Daddy Yankee", "spanish",
       ["reggaeton"], ["hype", "celebratory"], "2000s",
       94, 0.90, 0.90, 0.94, 192, ["throwback", "peak-time", "anthem"]),
    _t("trk_concalma_dy", "Con Calma", "Daddy Yankee & Snow", "spanish",
       ["reggaeton"], ["hype", "celebratory"], "2010s",
       94, 0.86, 0.90, 0.89, 193, ["peak-time", "sing-along"]),
    _t("trk_titime_bb", "Titi Me Pregunto", "Bad Bunny", "spanish",
       ["reggaeton"], ["hype", "celebratory"], "2020s",
       106, 0.88, 0.90, 0.91, 243, ["peak-time", "dembow"]),
    _t("trk_meportobonito_bb", "Me Porto Bonito", "Bad Bunny & Chencho Corleone", "spanish",
       ["reggaeton"], ["sensual", "celebratory"], "2020s",
       92, 0.80, 0.92, 0.93, 178, ["sing-along", "peak-time"]),
    _t("trk_dakiti_bb", "Dakiti", "Bad Bunny & Jhay Cortez", "spanish",
       ["reggaeton"], ["dark", "sensual"], "2020s",
       110, 0.76, 0.88, 0.91, 205, ["late-night", "peak-time"]),
    _t("trk_provenza_kg", "Provenza", "KAROL G", "spanish",
       ["reggaeton"], ["chill", "sensual"], "2020s",
       111, 0.60, 0.88, 0.89, 210, ["late-night", "sunset"]),
    _t("trk_tqg_kg", "TQG", "KAROL G & Shakira", "spanish",
       ["reggaeton"], ["celebratory", "sensual"], "2020s",
       96, 0.78, 0.90, 0.86, 199, ["sing-along", "peak-time"]),
    _t("trk_bichota_kg", "Bichota", "KAROL G", "spanish",
       ["reggaeton"], ["hype", "celebratory"], "2020s",
       96, 0.86, 0.90, 0.83, 165, ["peak-time", "dembow"]),
    _t("trk_hipsdontlie_sh", "Hips Don't Lie", "Shakira & Wyclef Jean", "spanish",
       ["pop", "reggaeton"], ["celebratory", "sensual"], "2000s",
       100, 0.88, 0.88, 0.97, 218, ["throwback", "sing-along", "peak-time"]),
    _t("trk_danzakuduro_do", "Danza Kuduro", "Don Omar & Lucenzo", "spanish",
       ["reggaeton"], ["hype", "celebratory"], "2010s",
       130, 0.90, 0.90, 0.93, 198, ["peak-time", "throwback", "sing-along"]),
    _t("trk_bailando_ei", "Bailando", "Enrique Iglesias", "spanish",
       ["pop", "reggaeton"], ["celebratory", "romantic"], "2010s",
       122, 0.85, 0.88, 0.94, 244, ["sing-along", "peak-time"]),
]


# ---------------------------------------------------------------------------
# Afrobeats / Amapiano
# ---------------------------------------------------------------------------

_AFRO: List[Track] = [
    _t("trk_lastlast_bu", "Last Last", "Burna Boy", "afrobeats",
       ["afrobeat"], ["nostalgic", "celebratory"], "2020s",
       102, 0.76, 0.86, 0.91, 173, ["sing-along", "heartbreak"]),
    _t("trk_ye_bu", "Ye", "Burna Boy", "afrobeats",
       ["afrobeat"], ["celebratory", "hype"], "2010s",
       106, 0.80, 0.88, 0.86, 205, ["sing-along", "peak-time"]),
    _t("trk_cityboys_bu", "City Boys", "Burna Boy", "afrobeats",
       ["afrobeat"], ["celebratory", "hype"], "2020s",
       104, 0.78, 0.86, 0.81, 190, ["peak-time", "groove"]),
    _t("trk_essence_wk", "Essence", "WizKid & Tems", "afrobeats",
       ["afrobeat", "rnb"], ["sensual", "chill"], "2020s",
       106, 0.60, 0.88, 0.93, 248, ["late-night", "sing-along", "wine"]),
    _t("trk_comecloser_wk", "Come Closer", "WizKid & Drake", "afrobeats",
       ["afrobeat"], ["sensual", "chill"], "2010s",
       104, 0.70, 0.88, 0.83, 200, ["late-night", "wine"]),
    _t("trk_calmdown_re", "Calm Down", "Rema & Selena Gomez", "afrobeats",
       ["afrobeat", "pop"], ["romantic", "celebratory"], "2020s",
       107, 0.75, 0.90, 0.97, 220, ["sing-along", "crossover", "peak-time"]),
    _t("trk_dumebi_re", "Dumebi", "Rema", "afrobeats",
       ["afrobeat"], ["celebratory", "chill"], "2010s",
       105, 0.75, 0.88, 0.81, 180, ["groove", "wine"]),
    _t("trk_water_ty", "Water", "Tyla", "afrobeats",
       ["amapiano", "afrobeat"], ["sensual", "celebratory"], "2020s",
       112, 0.76, 0.92, 0.95, 200, ["viral", "peak-time", "wine"]),
    _t("trk_truthordare_ty", "Truth or Dare", "Tyla", "afrobeats",
       ["amapiano"], ["sensual", "celebratory"], "2020s",
       113, 0.72, 0.90, 0.81, 165, ["groove", "wine"]),
    _t("trk_mnike_ti", "Mnike", "Tyler ICU & Tumelo.za", "afrobeats",
       ["amapiano"], ["hype", "celebratory"], "2020s",
       113, 0.82, 0.92, 0.76, 300, ["peak-time", "log-drum"]),
    _t("trk_unavailable_da", "Unavailable", "Davido & Musa Keys", "afrobeats",
       ["afrobeat", "amapiano"], ["celebratory", "hype"], "2020s",
       110, 0.80, 0.90, 0.86, 190, ["peak-time", "sing-along"]),
    _t("trk_fall_da", "Fall", "Davido", "afrobeats",
       ["afrobeat"], ["celebratory", "romantic"], "2010s",
       105, 0.76, 0.88, 0.86, 205, ["sing-along", "groove"]),
]


# ---------------------------------------------------------------------------
# Tracks from a real DJ set the product was demoed against. Added so the
# setlist-insertion engine has something to reason about -- the rest of the
# catalog skews a few years older than what this DJ actually plays.
#
# BPM and energy are estimates in the right ballpark, not Rekordbox-analysed
# values. They drive slot scoring directly, so if you have the real numbers
# from the DJ's software, replace them here first -- everything downstream
# (bpm_delta, half/double-time detection, energy arcs) inherits from them.
# ---------------------------------------------------------------------------

_LIVE_SET: List[Track] = [
    _t("trk_buzz_badshah", "Buzz", "Badshah & Aastha Gill", "hindi",
       ["desi_hiphop", "pop"], ["hype", "celebratory"], "2010s",
       100, 0.84, 0.88, 0.86, 195, ["peak-time", "badshah", "sing-along", "club"]),
    _t("trk_uyiamma_azaad", "Uyi Amma", "Madhubanti Bagchi", "hindi",
       ["bollywood"], ["hype", "sensual"], "2020s",
       104, 0.86, 0.90, 0.82, 180, ["peak-time", "item-number", "amit-trivedi", "azaad"]),
    _t("trk_taubataub_aujla", "Tauba Tauba", "Karan Aujla", "punjabi",
       ["desi_hiphop", "pop"], ["hype", "sensual"], "2020s",
       98, 0.82, 0.92, 0.94, 190, ["peak-time", "karan-aujla", "bad-newz", "viral"]),
    _t("trk_akhiyaan_mitraz", "Akhiyaan Gulaab", "Mitraz", "hindi",
       ["bollywood", "pop"], ["romantic"], "2020s",
       92, 0.54, 0.70, 0.88, 205, ["sing-along", "couples", "mitraz", "slow-burn"]),
    _t("trk_garmi_badshah", "Garmi", "Badshah & Neha Kakkar", "hindi",
       ["desi_hiphop", "bollywood"], ["hype", "aggressive"], "2020s",
       100, 0.90, 0.90, 0.90, 185, ["peak-time", "badshah", "street-dancer", "club"]),
]


TRACKS: List[Track] = (
    _LIVE_SET
    +
    _PUNJABI
    + _BOLLY_RETRO
    + _BOLLY_MODERN
    + _REGIONAL
    + _HIPHOP_RNB
    + _DANCE
    + _RETRO
    + _LATIN
    + _AFRO
)


__all__ = ["TRACKS"]
